language: node_js
node_js:
- '8'
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _book
  on:
    branch: master
env:
  global:
  - secure: 
  - secure: CrOHOKMTOU8j3O6xLMqQ8/sF68OeDl28Qxm82YWmh0uCY4a+UUjvT0UKoyMxXBAFxoW47n+31KqgWKCDmm2LnGagGakygtdQHlhTz+gcpD6U7Njng8qlFl98sausr7odjbHAsYmUIQ5f007pf8XOJYTjHa7bd17dgGeR40KG7YUgBZx6/xglvyrVZ2IzuJYQOZmTTuJbLfhcjdj/ESZaIEukm8NPhMxZG+34ty1ZAsx6F6BWUN+ZYWHfAu5pEGzJSG+4n6fv00T79L8QMgK/RSnIUBHOUX1/sqEtcYb0HBnKegxvZ+I2isOW8IIfFfJrewSu/m8S/k3iuG9dDoFVRcLGXLvaOTqkKm2+nQpZ4/T7dzSSGqnRhxmlknsplIvP/EoV+bUOZzXeVoIz0dDalLUq6XAQJk/4bEY3gpRjri1Z6LYFZUWtkTCG6cV8fkX0dX7fmnilUAn0tYGYPfJCia5WP+Mg+vJ/OVrUX3xKXhsWA0kTZnBsbXosJjE6GZMCxnh6B1lFxVjaGWa9UjLKxEah652EQr5aF5Z5x02EYgh2mzGGB+BCH+0f7iaapg575EnQdVK91A7i+HXF3hmSeIx8UkG22uJqwQV2D2mLcJsMgr7pqA/JesHMgE7Xsd8yuQbWUhzTAh6PW8me//4nLzKd8wHKCCMw1UGPF7JdeOY=
